[build-system]
requires = ["setuptools >= 65.5.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yoyodyne"
version = "0.2.2"
description = "Small-vocabulary neural sequence-to-sequence models"
readme = "README.md"
requires-python = ">= 3.9"
license = { text = "Apache 2.0" }
authors = [
    {name = "Adam Wiemerslage"},
    {name = "Kyle Gorman"},
    {name = "Travis Bartley"},
]
keywords = [
    "computational linguistics",
    "morphology",
    "natural language processing",
    "language",
]
dependencies = [
    "maxwell >= 0.2.0",
    "pytorch-lightning >= 1.7.0, <2.0.0",
    "torch >= 1.11.0, <2.0.0",
]
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Text Processing :: Linguistic",
]

[project.scripts]
yoyodyne-predict = "yoyodyne.predict:main"
yoyodyne-train = "yoyodyne.train:main"

[project.urls]
homepage = "https://github.com/CUNY-CL/yoyodyne"
